### PR TITLE
modified pre-test and deleted third test

### PR DESCRIPTION
**Pull request by podchasova11**
US_11-03-08_Trading_psychology_guide

1) modified pre-test  
2) deleted US_11-03-08_trading_psychology_guide_test.py

### CODE REVIEW

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frm RF_11.03.08_02 | Education > Menu Item [Trading psychology guide] > Test button [Try Demo] in Main banner](https://app.clickup.com/t/8692j9frm)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frj RF_11.03.08_01 | Education > Menu Item [Trading psychology guide] > Test button [Start trading] in Main banner](https://app.clickup.com/t/8692j9frj)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frp RF_11.03.08_03 | Education > Menu Item [Trading psychology guide] >Test button [Trade] in Widget "Most traded"](https://app.clickup.com/t/8692j9frp)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9ft6 AT_11.03.08.01_01 | Education > Menu Item [Trading psychology guide] > pages "Articles" selected in the list of Items > Test button [Start trading] in Main banner](https://app.clickup.com/t/8692j9ft6)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9ft8 AT_11.03.08.01_02 | Education > Menu Item [Trading psychology guide] > pages "Articles" selected in the list of Items >Test button [Try Demo] in Main banner](https://app.clickup.com/t/8692j9ft8)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9ftb AT_11.03.08.01_03 | Education > Menu Item [Trading psychology guide] > pages "Articles" selected in the list of Items >Test button [Trade] in Widget "Most traded"](https://app.clickup.com/t/8692j9ftb)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9ftg AT_11.03.08.01_06 | Education > Menu Item [Trading psychology guide] > Item Articles content blocks > Test button [1. Create & verify your account] in Block "Steps trading"](https://app.clickup.com/t/8692j9ftg)

**Review by AlexTom22 — APPROVED** [review]

**Pull request merged**
