### PR TITLE
US_11-03-01-01_trading_strategies_guide_test

### PR DESCRIPTION
**Pull request by podchasova11**
US_11-03-01-01_trading_strategies_guide_test

Added to the tests two languages "zh", "ru" in that child US

### CODE REVIEW

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fm6 Py/RF_11.03.01.01_01 | Educations > Menu item [Trading Strategies Guide] > pages "Articles" selected in the list of Items >Test button [Start Trading] in Trading Strategies Guide Main banner](https://app.clickup.com/t/8692j9fm6)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fm7 Py/RF_11.03.01.01_02 | Educations > Menu item [Trading Strategies Guide] > pages "Articles" selected in the list of Items >Test button [Try demo] in Trading Strategies Guide Main banner](https://app.clickup.com/t/8692j9fm7)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fm3 Py/RF_11.03.01.01_03 | Educations > Menu item [Trading Strategies Guide] > pages "Articles" selected in the list of Items > Test button [Trade] in Widget Side-tab [Most traded]](https://app.clickup.com/t/8692j9fm3)

**Comment by podchasova11** [comment]
Task linked: [CU-8692t70ed Py/RF_11.03.01.01_08 | Educations > Menu item [Trading Strategies Guide] > pages "Articles" selected in the list of Items  > Test button [Explore Web Platform] in Block "Sign up and trade smart today!"](https://app.clickup.com/t/8692t70ed)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fma Py/RF_11.03.01.01_09 | Educations > Menu item [Trading Strategies Guide] > pages "Articles" selected in the list of Items >Test button [1. Create & verify your account] in Block "Steps trading"](https://app.clickup.com/t/8692j9fma)

**Review by AlexTom22 — APPROVED** [review]

**Pull request merged**
