### PR TITLE
Modified  US_11.03.08

### PR DESCRIPTION
**Pull request by podchasova11**
Modified descriptions in US_11.03.08

### CODE REVIEW

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frj AT_11.03.08_01 | Education > Menu Item [Trading psychology guide] > Test button [Start trading] in Main banner](https://app.clickup.com/t/8692j9frj)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frm AT_11.03.08_02 | Education > Menu Item [Trading psychology guide] >Test button [Try Demo] in Main banner](https://app.clickup.com/t/8692j9frm)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frp AT_11.03.08_03 | Education > Menu Item [Trading psychology guide] >Test button [Trade] in Widget "Most traded"](https://app.clickup.com/t/8692j9frp)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9frq AT_11.03.08_04| Education > Menu Item [Trading psychology guide] > Test button [1. Create & verify your account] in Block "Steps trading"](https://app.clickup.com/t/8692j9frq)

**Review by AlexTom22 — APPROVED** [review]

**Pull request merged**
