### PR TITLE
Refactoring tests, check language  US_11-03-01

### PR DESCRIPTION
**Pull request by podchasova11**
US_11-03-01_trading-strategies-guide_test.py

Refactoring tests, check for language 

Рефакторинг тестов 06, 07, 08, 09 в US_11-03-01

### CODE REVIEW

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fm1 AT_11.03.01_07 | Educations > Menu item [Trading Strategies Guide] > Test button [Get it on Google Play] in Block "Sign up and trade smart today!"](https://app.clickup.com/t/8692j9fm1)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fkz RF_11.03.01_06 | Educations > Menu item [Trading Strategies Guide] > Test button  [Download on the App Store] in Block "Sign up and trade smart today!"](https://app.clickup.com/t/8692j9fkz)

**Comment by podchasova11** [comment]
Task linked: [CU-8692t70ed RF_11.03.01_08 | Educations > Menu item [Trading Strategies Guide] > Test button [Explore Web Platform] in Block "Sign up and trade smart today!"](https://app.clickup.com/t/8692t70ed)

**Comment by podchasova11** [comment]
Task linked: [CU-8692j9fma RF_11.03.01_09 | Educations > Menu item [Trading Strategies Guide]>Test button [1. Create & verify your account] in Block "Steps trading"](https://app.clickup.com/t/8692j9fma)

**Review by AlexTom22 — APPROVED** [review]
остается сделать проверку на языки тк_01, _02 и _03

**Pull request merged**
