### PR TITLE
add us_11-03-04, us_11-03-05, us_11-03-06

### PR DESCRIPTION
**Pull request by AndrSam1**

### CODE REVIEW

**Review by AlexTom22 — APPROVED** [review]

**Comment by AndrSam1** [comment]
[AT_11.03.06_07 | Educations > Menu item [Scalp Trading] > Test button [1. Create & verify your account] in Block "Steps trading"](https://trello.com/c/AKY1Ky9r/205-at11030607-educations-menu-item-scalp-trading-test-button-1-create-verify-your-account-in-block-steps-trading)

**Comment by AndrSam1** [comment]
[AT_11.03.06_06 | Educations > Menu item [Scalp Trading] > Test button [Explore Web Platform] in Block "Sign up and trade smart today!"](https://trello.com/c/U74EBBfW/204-at11030606-educations-menu-item-scalp-trading-test-button-explore-web-platform-in-block-sign-up-and-trade-smart-today)

**Comment by AndrSam1** [comment]
[AT_11.03.06_05 | Educations > Menu item [Scalp Trading] > Test button [Get it on Google Play] in Block "Sign up and trade smart today!"](https://trello.com/c/7zd82Pkm/203-at11030605-educations-menu-item-scalp-trading-test-button-get-it-on-google-play-in-block-sign-up-and-trade-smart-today)

**Comment by AndrSam1** [comment]
[AT_11.03.06_04 | Educations > Menu item [Scalp Trading] > Test button [Download on the App Store] in Block "Sign up and trade smart today!"](https://trello.com/c/GtPowLdH/202-at11030604-educations-menu-item-scalp-trading-test-button-download-on-the-app-store-in-block-sign-up-and-trade-smart-today)

**Comment by AndrSam1** [comment]
[AT_11.03.06_03 | Educations > Menu item [Scalp Trading] > Test button [Trade] on Widget "Most Traded"](https://trello.com/c/RYbQXO3P/201-at11030603-educations-menu-item-scalp-trading-test-button-trade-on-widget-most-traded)

**Comment by AndrSam1** [comment]
[AT_11.03.06_02 | Educations > Menu item [Scalp Trading] > Test button [Try Demo] on Main banner](https://trello.com/c/lzMyCDZ7/200-at11030602-educations-menu-item-scalp-trading-test-button-try-demo-on-main-banner)

**Comment by AndrSam1** [comment]
[AT_11.03.04_01 | Educations > Menu item [Position Trading] > Test button [Start trading] on Main banner](https://trello.com/c/PIySQzdG/208-at11030401-educations-menu-item-position-trading-test-button-start-trading-on-main-banner)

**Comment by AndrSam1** [comment]
[AT_11.03.04_02 | Educations > Menu item [Position Trading] > Test button [Try Demo] on Main banner](https://trello.com/c/BL9uwUxJ/209-at11030402-educations-menu-item-position-trading-test-button-try-demo-on-main-banner)

**Comment by AndrSam1** [comment]
[AT_11.03.04_03 | Educations > Menu item [Position Trading] > Test button [Trade] on Widget "Most Traded"](https://trello.com/c/aacNjy2i/210-at11030403-educations-menu-item-position-trading-test-button-trade-on-widget-most-traded)

**Comment by AndrSam1** [comment]
[AT_11.03.04_06 | Educations > Menu item [Position Trading] > Test button [Explore Web Platform] in Block "Sign up and trade smart today!"](https://trello.com/c/r4WGPHhO/213-at11030406-educations-menu-item-position-trading-test-button-explore-web-platform-in-block-sign-up-and-trade-smart-today)

**Comment by AndrSam1** [comment]
[AT_11.03.04_07 | Educations > Menu item [Position Trading] > Test button [1. Create & verify your account] in Block "Steps trading"](https://trello.com/c/DCxqDj81/214-at11030407-educations-menu-item-position-trading-test-button-1-create-verify-your-account-in-block-steps-trading)

**Pull request merged**
